# permissions for end users to view podcs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: podc-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: podc
    app.kubernetes.io/part-of: podc
    app.kubernetes.io/managed-by: kustomize
  name: podc-viewer-role
rules:
- apiGroups:
  - zw.zw.com
  resources:
  - podcs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - zw.zw.com
  resources:
  - podcs/status
  verbs:
  - get
